version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: future_lab_backend
    network_mode: "host"
    volumes:
      - /home/future-lab/B002_Future_Lab_Bots/cobot:/cobot
      - /home/future-lab/B002_Future_Lab_Bots:/home/future-lab/B002_Future_Lab_Bots
      - /opt/ros/jazzy:/opt/ros/jazzy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/future-lab/.Xauthority:/root/.Xauthority:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/root/.Xauthority
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: future_lab_frontend
    network_mode: "host"
    env_file:
      - .env
    restart: unless-stopped
